name: Monthly cron job for event e-mails
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request POST \
          --url 'https://cognatus.herokuapp.com/api/event-email' \
          --header 'Authorization: Bearer ${{ secrets.EVENT_EMAIL_KEY }}'
